steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sunlit-context-430703-g8/yolo-app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sunlit-context-430703-g8/yolo-app:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'yolo-app',
           '--image', 'gcr.io/sunlit-context-430703-g8/yolo-app:$COMMIT_SHA',
           '--region', 'asia-northeast3',
           '--platform', 'managed',
           '--allow-unauthenticated']

images:
  - 'gcr.io/sunlit-context-430703-g8/asia-northeast3:$COMMIT_SHA'
options:
  logs_bucket: gs://gcr.io