options:
  logging: CLOUD_LOGGING_ONLY  # 로그를 Cloud Logging에만 기록하도록 설정


steps:
  # 1. 모든 모델 파일을 GCS에서 다운로드
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://sushi-model/sushi9or11s.pt', './sushi9or11s.pt']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://sushi-model/yolo11s-1010.pt', './modyolo11sel2.pt']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://sushi-model/yolov8m_v3.pt', './yolov8m_v3.pt']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://sushi-model/yolov8n.pt', './yolov8n.pt']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://sushi-model/yolov8s.pt', './yolov8s.pt']

  # 2. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sunlit-context-430703-g8/yolo-app', '.']

  # 3. Cloud Run 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'yolo-app',
        '--image', 'gcr.io/sunlit-context-430703-g8/yolo-app',
        '--platform', 'managed',
        '--region', 'asia-northeast3',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.iosunlit-context-430703-g8/yolo-app'
